### ISSUE TITLE
New Bank account demo failure

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/sandbox#1371]
https://github.com/trustbloc/sandbox/runs/5130457833?check_suite_focus=true#step:6:264

> failed to connect TypeError: this.credentialManager.saveManifestCredential is not a function
>     at oe.connect (didConn.js:73:32)
>     at async Proxy.connect (DIDConnect.vue:143:7)

**Comment by novalina26** [comment]
@silveraid
